/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RoundNum = number;
export type CurrentTeam = number;
export type ActiveEntity = string | null;
export type Name = string;
export type Hp = number;
/**
 * @minItems 2
 * @maxItems 2
 */
export type Point = [unknown, unknown];
export type Team = number;
export type MoveActions = number;
export type StandardActions = number;
export type FreeActions = number;
export type Entities = EntityState[];
export type Actor = string;
export type Target = string;
export type Ability = string;
export type Path = Point[] | null;
export type MovementName = string;
export type Reward = number;
export type Done = boolean;

export interface LogEntry {
  before_state: EngineState;
  action: ActionState;
  after_state: EngineState;
  reward: Reward;
  done: Done;
  [k: string]: unknown;
}
export interface EngineState {
  round_num: RoundNum;
  current_team: CurrentTeam;
  active_entity: ActiveEntity;
  entities: Entities;
  [k: string]: unknown;
}
export interface EntityState {
  name: Name;
  hp: Hp;
  pos: Point;
  team: Team;
  move_actions: MoveActions;
  standard_actions: StandardActions;
  free_actions: FreeActions;
  [k: string]: unknown;
}
export interface ActionState {
  actor: Actor;
  move_pos: Point;
  target: Target;
  ability: Ability;
  path?: Path;
  movement_name?: MovementName;
  [k: string]: unknown;
}
