/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WinnerTeam = number | null;
export type RoundNum = number;
export type CurrentTeam = number;
export type ActiveEntity = number | null;
export type Id = number;
export type Name = string;
export type Hp = number;
/**
 * @minItems 2
 * @maxItems 2
 */
export type Point = [unknown, unknown];
export type Team = number;
export type MoveActions = number;
export type StandardActions = number;
export type FreeActions = number;
export type Entities = EntityState[];
export type Actor = number;
export type Target = number | null;
export type Ability = string;
export type MovePath = Point[] | null;
export type MovementName = string;
export type Done = boolean;
export type Done1 = boolean;
export type WinnerTeam1 = number | null;
export type Simulations = ActionSim[];
export type Logs = LogEntry[];

export interface GameLog {
  winner_team: WinnerTeam;
  logs: Logs;
  [k: string]: unknown;
}
export interface LogEntry {
  before_state: EngineState;
  action: ActionState;
  after_state: EngineState;
  done: Done;
  simulations?: Simulations;
  [k: string]: unknown;
}
export interface EngineState {
  round_num: RoundNum;
  current_team: CurrentTeam;
  active_entity: ActiveEntity;
  entities: Entities;
  [k: string]: unknown;
}
export interface EntityState {
  id: Id;
  name: Name;
  hp: Hp;
  pos: Point | null;
  team: Team;
  move_actions: MoveActions;
  standard_actions: StandardActions;
  free_actions: FreeActions;
  [k: string]: unknown;
}
export interface ActionState {
  actor: Actor;
  target: Target;
  ability: Ability;
  move_path: MovePath;
  movement_name?: MovementName;
  [k: string]: unknown;
}
export interface ActionSim {
  action: ActionState;
  after_state: EngineState;
  done: Done1;
  winner_team?: WinnerTeam1;
  [k: string]: unknown;
}
